version: '3'

services:
  lock-service:
    build: .
    container_name: lock-service
    restart: always
    ports:
      - 50051:50051
    environment:
      REDIS_HOST: "redis"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379