name: GitHub Actions
on:
  push:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.15.0 ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up environment
        run: docker-compose -f docker-compose-storage-only.yml up -d
      - name: Wait for docker to finish building
        run: sleep 30
      - name: install modules
        run: npm install
      - name: start project
        run: npm start &
      - name: test project
        run: npm test
